### ISSUE TITLE
MPI: Only make  rank 0 write output

### ISSUE THREAD

**Issue by NilsNiggemann** [NilsNiggemann/PMFRG.jl#21]
In the docs it says 

> In the following code snippet, a rank-specific path for MainFile and for CheckPointDirectory is created, in order to avoid writing conflicts between ranks:

I think we want to change this in the future so that only rank 0 interacts with IO. The mainFile is only written to at the end of the computation, and the Checkpoints are also never interacted with except between ODE steps, so we can probably do a simple check.

The most likely fix is to add a dispatch the methods `setCheckpoint` `saveMainOutput` for `UseMPI()`.

**Comment by mmesiti** [comment]
Saving only on rank 0 requires for that process which rank it represent. Typically, one calls `MPI.comm_rank(MPI.COMM_WORLD)`, but this is not something we want to add to the main code that should be totally independent from MPI. 

For that, we could save the rank of the process inside the `UseMPI` structure. 

I would then change `UseMPI` in this way:
```
struct UseMPI <: AbstractParallelizationScheme
    rank::Int64
    nranks::Int64
end
```
so then at least in the parallelization scheme object we have the information to decide whether we should print/save or not.

**Comment by mmesiti** [comment]
This is somewhat related to #18, where we also think about storing stuff inside a `ParallelizationScheme`.

**Comment by mmesiti** [comment]
I am trying this idea
```
struct UseMPI <: AbstractParallelizationScheme
    rank::Int64
    nranks::Int64
end
```
but I do not exactly how to go forward. One should pass the parallelization scheme down the call tree, and then dispatch on its concrete type. The methods for `UseMPI` should then go into the extension, do the rank check and if the rank is 0 call the methods defined in the main package. I can code this, I think.

A cheaper alternative would be to change `Par.Options.MinimalOutput` into `Par.Options.OutputMode`  (i.e., changing the member of `OptionParams`) with type `@enum OutputMode  None Bare Verbose`, and then at the top level pass the value we want based on the rank, for example
```

Solution, saved_values = SolveFRG(
    Par,
    UseMPI(rank,nranks),
    MainFile = mainFile,
    CheckpointDirectory = flowpath,
    method = DP5(),
    VertexCheckpoints = [],
    CheckPointSteps = 3,
    OutputMode = (rank!=0)? NoOutput : VerboseOutput,
)
```
In this way, none of the output will ever need to know about how many ranks we have, and we can still decide at the top level whether we want all ranks to print or not.

What do you think?

**Comment by NilsNiggemann** [comment]
> but I do not exactly how to go forward. One should pass the parallelization scheme down the call tree, and then dispatch on its concrete type. The methods for UseMPI should then go into the extension, do the rank check and if the rank is 0 call the methods defined in the main package. I can code this, I think.

Yes that was kind of what I was thinking of. I like your second idea though and perhaps we can do it even simpler:

```
function SolveFRG(Par,ParallelizationScheme::UseMPI;MainFile = nothing,CheckpointDirectory = nothing,kwargs...,
) 
    MainFile = ParallelizationScheme.rank == 0 ? MainFile : nothing
    CheckpointDirectory = ParallelizationScheme.rank == 0 ? CheckpointDirectory : nothing
    
    launchPMFRG!(
        InitializeState(Par),
        AllocateSetup(Par, ParallelizationScheme),
        getDeriv!;
        MainFile = nothing,
        CheckpointDirectory = nothing,
        kwargs...,
    )
end
```
This function catches the arguments and passes `nothing` to `launchPMFRG` if the rank is not the main rank (in which case there will be no writing of the mainFile/Checkpoints. 

As of yet, one still needs to handle the IO somehow but this requires a little change anyway:
- I think we should deprecate the option `MinimalOutput` in Params. This also fits better with the design philosophy that Params should only handle things which are inherent to the numerical approximations/parameters used, while solver options (UseMPI, MainFile, ODE method etc) are passed to `SolveFRG` instead
- instead, we should add a keyword arg `verbose = true` to SolveFRG. If set to `false` **all** output should be switched off
- Then, we can similarly catch this option in the code above, and pass false if the rank is not the main rank

One could argue that this is a very minor breakage in the sense that code that used the MinimalOutput=false flag might now print more output but in any case the exact amount of output that is printed is anyway not really something that code should rely upon.

**Comment by NilsNiggemann** [comment]
I think since there are a few ways to do this, lets not rush this for the current release. Perhaps it would be best for now to update the Readme.md to the following instead:

```
using MPI

MPI.Init()
rank = MPI.Comm_rank(MPI.COMM_WORLD)

Par = Params(
    System,
    T=0.5,
    N = 10,
    MinimalOutput = rank == 0,
)
[...]

tempdir = "temp_rank$rank"
mainFile = "$tempdir/" * PMFRG.generateFileName(Par, "_testFile")
flowpath = "$tempdir/flows/"

if rank != 0
   mainFile = nothing
   flowpath = nothing
end

Solution, saved_values = SolveFRG(
    Par,
    UseMPI(),
    MainFile = mainFile,
    CheckpointDirectory = flowpath,
    method = DP5(),
    VertexCheckpoints = [],
    CheckPointSteps = 3,
)


MPI.Finalize()
```
This should ensure that no unneccesary output is generated and requires Minimal changes of the batch script

**Comment by mmesiti** [comment]
So, as a form of very masochist exercise, and because I started before reading your comments, and out of curiosity, I tried the "store rank info in `UseMPI` and dispatch on it"-approach. It's been quite [a bloodbath](https://github.com/mmesiti/PMFRG.jl/commit/7a6b448836c7a5cfaca8ad5b09eabdbfb024f852), that required changing quite some code an write a lot of boilerplate. Some of the boilerplate could possibly be removed with a macro, but the macro might actually be quite complex and not worth the effort. 

Defintely defining 
```
if rank != 0
   mainFile = nothing
   flowpath = nothing
end
```
seems a much simpler alternative, although it forces the user to manage this (but also it gives the possibility to manage it ).

**Comment by mmesiti** [comment]
By the way, it was good idea to have all those methods dispatch on `nothing` as well as an escape hatch.

**Comment by NilsNiggemann** [comment]
wow you're right that first dispatch idea is a lot more than I thought it would be. 
Thanks for opening the PR - I will also check tomorrow whether there might be any stray print statements (Im not sure if I ever took `MinimalOutput` that seriously but that should be easy to find out). Then there really should be everything done to make the release (*knocks on wood)
