### ISSUE TITLE
Does "setupFromCheckpoint" still exist?

### ISSUE THREAD

**Issue by mmesiti** [NilsNiggemann/PMFRG.jl#32]
I see it is still exported in src/PMFRG.jl, but I do not see it defined anywhere.

Looking at the output of `git log -p -S setupFromCheckpoint`,it seems that the function was deleted in da1b042d83f3dcb38334cc2edb1fc6a34eaaf0bc.

**Comment by NilsNiggemann** [comment]
resolved in https://github.com/NilsNiggemann/PMFRG.jl/commit/ef1530ebb1d7e46915ced2176a3b54dce98bee8e
